### PR TITLE
Bump python_requires version cap

### PR DESCRIPTION
**Pull request by 92kns**
I previously had to downgrade my python to install mozperftest-tools locally but i'd prefer to stay on 3.10. (I was mainly using artifact downloader, but figure this might be useful to bump up for others)

doing this seems to work- any reason to not bump this?

### CODE REVIEW

**Comment by gmierz** [comment]
@92kns I think this will be okay to bump. We have code here that handles that: https://github.com/mozilla/mozperftest-tools/blob/master/mozperftest_tools/setup.py#L23-L27

Note though that the reason it's working in 3.10 for you is because we're not pinning the reqs (which we should).

@alexandru-io what do you think?

**Comment by alexandru-io** [comment]
> Note though that the reason it's working in 3.10 for you is because we're not pinning the reqs (which we should).
> 
> @alexandru-io what do you think?

I agree, pinning reqs is a best practice.

**Review by gmierz — APPROVED** [review]
r+ thanks @92kns! Could you file a follow-up issue in jira to pin these depedencies?

**Comment by 92kns** [comment]
thanks for the quick rev
jira for pinning: https://mozilla-hub.atlassian.net/browse/FXP-2636

**Pull request merged**
